module.exports = {
  knowledge: [
    {
      type: 'category',
      label: 'Start Here',
      collapsed: false,
      items: [
        '00-start-here/master-continuity-brief',
        '00-start-here/current-state',
        '00-start-here/operational-narrative',
        '00-start-here/package-index',
        '00-start-here/shared-definitions',
        '00-start-here/extraction-report',
      ],
    },
    {type: 'autogenerated', dirName: '10-business'},
    {type: 'autogenerated', dirName: '20-product'},
    {type: 'autogenerated', dirName: '30-evidence'},
    {type: 'autogenerated', dirName: '40-market'},
    {type: 'autogenerated', dirName: '50-execution'},
    {type: 'autogenerated', dirName: '60-history'},
    {type: 'autogenerated', dirName: '90-registers'},
  ],
};
