module.exports = {
  knowledge: [
    {
      type: 'category',
      label: 'Start Here',
      collapsed: false,
      items: [
        'start-here/human-blockchain-master-continuity-brief-001',
        'start-here/current-state',
        'start-here/operational-narrative',
        'start-here/package-index',
        'start-here/shared-definitions',
        'start-here/extraction-report-src-010',
      ],
    },
    {type: 'autogenerated', dirName: '10-business'},
    {type: 'autogenerated', dirName: '20-product'},
    {type: 'autogenerated', dirName: '30-evidence'},
    {type: 'autogenerated', dirName: '40-market'},
    {type: 'autogenerated', dirName: '50-execution'},
    {type: 'autogenerated', dirName: '60-history'},
    {type: 'autogenerated', dirName: '90-registers'},
  ],
};
